name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Go build 
        # You may pin to the exact commit or the version.
        # uses: cedrickring/golang-action@382e630a8e1ec81acc05518fdd4498a7c2a68ba6
        uses: cedrickring/golang-action@1.6.0
        with: 
          args: go build ./...
        env:
          GO111MODULE: "on"
          
      - name: Go test 
        # You may pin to the exact commit or the version.
        # uses: cedrickring/golang-action@382e630a8e1ec81acc05518fdd4498a7c2a68ba6
        uses: cedrickring/golang-action@1.6.0
        with: 
          args: go test ./pir ./updatable ./driver 
        env:
          GO111MODULE: "on"

  test_android_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: android-actions/setup-android@v2
      - name: Install Android Platform
        run: |
          sdkmanager "build-tools;30.0.3" "emulator" "patcher;v4" "platform-tools"  "platforms;android-29"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Gomobile
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          gomobile init
      - name: Build Gomobile Library
        run: |
          export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
          export ANDROID_NDK_TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
          gomobile bind -o android/app/testing.aar -target android/arm64 ./testing
      - name: Build APK 
        working-directory: ./android
        run: |
          touch ./trace.txt
          ./gradlew build -PtraceFile=../trace.txt
      - name: Build Instrumentation Tests
        run: ./gradlew assembleAndroidTest
        working-directory: ./android
